import { defineConfig } from "vite";
import tailwindcss from "@tailwindcss/vite";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Compiles app/globals.css (Tailwind v4 source, `@import "tailwindcss"`) into
// a real standalone stylesheet for design-sync's cfg.cssEntry — design-sync
// scrapes a compiled stylesheet, not the raw Tailwind source directives.
// Entry is a trivial CSS-only re-export (.design-sync/.cache/css-entry.ts,
// generated by build:design-system); this build only ever emits CSS.
export default defineConfig({
  plugins: [tailwindcss()],
  publicDir: false,
  build: {
    outDir: "dist-design-system",
    emptyOutDir: false,
    cssCodeSplit: false,
    lib: {
      entry: path.resolve(__dirname, ".design-sync/.cache/css-entry.ts"),
      formats: ["es"],
      fileName: () => "css-entry.js",
    },
  },
});
