import { useCallback, useEffect, useMemo, useState } from "react";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";

/**
 * NEO-101 — "Regenerate", and the source fields behind a generated title.
 *
 * ## Why the title needs a rebuild button at all
 *
 * `listingTitle` is written ONCE, at card creation, and never regenerated by a
 * sync (NEO-24/NEO-25's write-once rule — a re-sync must never stomp an
 * operator's wording). That rule is right, and it has one cost: a card whose
 * player, set or variation was corrected AFTER creation keeps a title built
 * from the old facts, and nothing in the product will ever fix it. This is the
 * one deliberate escape hatch, driven by the operator, one card at a time.
 *
 * ## Why the source chips ship with it
 *
 * The generator drops optional tokens until the title fits, so a title at the
 * cap is a title with something MISSING, and the missing thing is invisible in
 * the field. Rendering the inputs the title was built from turns "shorten this"
 * from a guessing game into an edit: the operator can see that "Image
 * Variation; Wearing sunglasses" is what pushed it over, and shorten THAT
 * rather than hacking at the player's name. The chips are plain text and never
 * links — a card's variation text is operator- and marketplace-sourced content,
 * not a destination.
 *
 * ## Laziness
 *
 * `previewListingTitle` is a real server round-trip per card, and the drawer
 * opens on every card an operator arrows through. So the query stays `"skip"`
 * until the operator asks for it, and then stays subscribed for the life of the
 * component so a second Regenerate is instant and the chips keep rendering.
 */

/** One labelled source fact, e.g. `Set` → `Topps Chrome`. */
export type TitleSourceChip = { label: string; value: string };

type PreviewResult = {
  title: string;
  coreFits: boolean;
  dropped: string[];
  inputs: {
    cardNumber: string;
    playerNames: string[];
    year?: string;
    manufacturer?: string;
    setName?: string;
    parallelName?: string;
    isRookie?: boolean;
    isRelic?: boolean;
    autographed?: string;
    shortPrint?: string;
    printRun?: number;
    cardVariation?: string;
    /**
     * Stored team names, verbatim. Declared OPTIONAL although the query always
     * returns it (possibly empty): a browser holding this bundle can be reading
     * an older deploy that predates the field, and a `.map` on `undefined`
     * inside a modal dialog takes the whole dialog with it.
     */
    teamNames?: string[];
    /** e.g. "Baseball". Optional for the same reason, and genuinely absent for
     * a set whose sport was never resolved. */
    sport?: string;
  };
};

/**
 * Format one input as a chip value, or drop it.
 *
 * Takes `unknown` on purpose: the flag fields on `ListingCardInputs` are a mix
 * of booleans and strings, and this module must not go stale when one of them
 * changes shape server-side. `true` renders the label itself (a boolean
 * `isRookie` becomes the chip `RC`), which is also how the generator words it.
 */
function chipValue(value: unknown, whenTrue: string): string | null {
  if (value == null || value === false || value === "") return null;
  if (value === true) return whenTrue;
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return value;
  return null;
}

/**
 * The chips for a preview, in the order the generator itself assembles a title:
 * core facts first (year, manufacturer, set, parallel, players, number), then
 * the optional tokens that get dropped from the end when it does not fit.
 *
 * Reading the row left to right therefore reads the title left to right, which
 * is what makes "the last chips are the ones at risk" legible without saying so.
 */
export function titleSourceChips(inputs: PreviewResult["inputs"]): TitleSourceChip[] {
  const chips: TitleSourceChip[] = [];
  const push = (label: string, value: unknown, whenTrue = label) => {
    const v = chipValue(value, whenTrue);
    if (v !== null) chips.push({ label, value: v });
  };

  // Core first, in the order the generator lays it down.
  push("Year", inputs.year);
  push("Maker", inputs.manufacturer);
  push("Set", inputs.setName);
  // One chip per player, not a joined string: on a multi-player card the names
  // are what an operator weighs against each other when shortening.
  for (const name of inputs.playerNames ?? []) {
    if (name) chips.push({ label: "Player", value: name });
  }
  if (inputs.cardNumber) chips.push({ label: "Number", value: `#${inputs.cardNumber}` });

  // Then the optional tokens, in the priority the generator appends them:
  // AUTO → RELIC → parallel → /printRun → variation → RC → SP/SSP → team(s) →
  // sport. The last chips are therefore the first to be dropped when a title
  // does not fit, which is the whole reason this row is ordered at all.
  push("Auto", inputs.autographed, "AUTO");
  push("Relic", inputs.isRelic, "RELIC");
  push("Parallel", inputs.parallelName);
  if (inputs.printRun != null) chips.push({ label: "Print run", value: `/${inputs.printRun}` });
  push("Variation", inputs.cardVariation);
  push("Rookie", inputs.isRookie, "RC");
  push("Short print", inputs.shortPrint, "SP");
  // One chip per team, matching the per-player treatment: a card can carry
  // two, and "which of these is worth the characters" is the same judgement.
  for (const name of inputs.teamNames ?? []) {
    if (name) chips.push({ label: "Team", value: name });
  }
  push("Sport", inputs.sport);

  return chips;
}

export type TitlePreview = {
  /** The source facts behind the last preview. Empty until one is fetched. */
  chips: TitleSourceChip[];
  /** Tokens the generator had to drop to fit the cap. Empty until fetched. */
  dropped: string[];
  /** A regenerate is in flight (or its query has not resolved yet). */
  loading: boolean;
  /**
   * A regenerate was asked for over a dirty draft and is waiting for a second
   * click. Surfaces as a confirm line, never a `window.confirm` — a browser
   * dialog steals focus out of the drawer and cannot be styled or tested.
   */
  confirming: boolean;
  /** Ask for a fresh title. Pass whether the draft has unsaved edits. */
  request: (dirty: boolean) => void;
  /** Drop a pending confirm — call it when the operator edits the draft again. */
  cancelConfirm: () => void;
};

/**
 * @param cardId the card to preview a title for
 * @param applyTitle where a fetched title lands. Pass a `useState` setter: it
 *   is a dependency of the apply effect, so an inline arrow would re-run it.
 */
export function useTitlePreview(
  cardId: Id<"cardChecklist">,
  applyTitle: (title: string) => void,
): TitlePreview {
  // Once true, stays true: the subscription is cheap to keep and expensive to
  // re-establish, and the chips must survive after the title has been applied.
  const [subscribed, setSubscribed] = useState(false);
  const [pending, setPending] = useState(false);
  const [confirming, setConfirming] = useState(false);

  // Typed by annotation rather than a cast: the generated return type has to be
  // assignable to `PreviewResult`, so a backend field that changes shape breaks
  // this line instead of quietly rendering nothing.
  const preview: PreviewResult | undefined = useQuery(
    api.selectorOptions.previewListingTitle,
    subscribed ? { cardId } : "skip",
  );

  useEffect(() => {
    if (!pending || preview === undefined) return;
    applyTitle(preview.title);
    // Reacting to a server response landing, not deriving render state — the
    // query is async and there is no render in which both "asked" and "has an
    // answer" are known without this.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setPending(false);
  }, [pending, preview, applyTitle]);

  const request = useCallback(
    (dirty: boolean) => {
      // A dirty draft is the operator's own wording. Replacing it is a real
      // loss, so it costs a second, deliberate click.
      if (dirty && !confirming) {
        setConfirming(true);
        return;
      }
      setConfirming(false);
      setSubscribed(true);
      setPending(true);
    },
    [confirming],
  );

  const cancelConfirm = useCallback(() => setConfirming(false), []);

  // `preview?.inputs` rather than `preview`: this hook renders inside a modal
  // dialog, and a response missing its `inputs` (a bundle reading an older
  // deploy's return shape) must show no chips, not throw the dialog away.
  const chips = useMemo(
    () => (preview?.inputs ? titleSourceChips(preview.inputs) : []),
    [preview],
  );

  return {
    chips,
    dropped: preview?.dropped ?? [],
    loading: pending,
    confirming,
    request,
    cancelConfirm,
  };
}
