/**
 * NEO-312 — how a NEW `cardChecklist` row is born, in one place.
 *
 * ## Why this exists
 *
 * Until now the only code that minted a marketplace-derived card row was the
 * insert branch of `commitCardChecklistChunk` (`selectorOptions.ts`): merge the
 * leaf's feature snapshot with what the card itself shows, default Signed By,
 * generate the write-once listing title and description, insert, then patch in
 * the SKU. NEO-312's parallel build copies an insert's cards onto each of its
 * parallels, and every one of those copies has to be born the same way — a
 * copy whose title was generated by a second implementation would disagree
 * with `previewListingTitle`'s Regenerate the moment the two drifted.
 *
 * So the branch body moved here verbatim and both callers share it. What the
 * CALLER still decides is everything that differs between them: the commit
 * resolves players and teams from a review, bounds the pending names and
 * applies the leaf's set-level team default; the parallel build copies those
 * from the insert's card. This module only turns a decided card into a row.
 *
 * ## What it never does
 *
 * It writes no `imageUrls` (a scan belongs to the physical card an operator
 * photographed, not to a checklist entry) and queues no enrichment. Its only
 * read is the caller's lazy `sport()` for the NEO-313 player index. `autographType` is folded into
 * `features.autographed` and is not stored (NEO-217).
 */

import type { WithoutSystemFields } from "convex/server";
import type { MutationCtx } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { deriveCardObservedFeatures } from "./features/deriveCardFeatures";
import {
  assessListingTitle,
  generateListingDescription,
  type ListingCardInputs,
} from "./features/generateListing";
import { generateSku } from "./sku";
import { syncCardPlayerLinks } from "./cardPlayerLinks";

/** Set-level values resolved once per commit (or per build page). */
export type CardRowSetContext = {
  sportSkuCode?: string;
  sportValue: string;
  setNameValue?: string;
  /** NEO-272 — the manufacturer's brand-unknown ROLE; absent = known. */
  manufacturerBrandUnknown?: boolean;
  /** The leaf row's complete `features` snapshot (NEO-71-74). */
  inheritedFeatures?: Record<string, string>;
};

/**
 * NB-owned fields a COPY carries verbatim from the card it copies (NEO-312).
 * The commit never passes these: a card born from a marketplace sync has no
 * team check, no operator ruling and no variation link yet.
 */
export type CarriedCardFields = Partial<
  Pick<
    Doc<"cardChecklist">,
    | "teamCheckDoneAt"
    | "bscTeamName"
    | "teamNoneConfirmedAt"
    | "teamNoneConfirmedByUserId"
    | "variationOfCardId"
    | "variationParentManual"
  >
>;

/** A card whose content has been decided, ready to become a row. */
export type NewCardRow = {
  selectorOptionId: Id<"selectorOptions">;
  cardNumber: string;
  cardName: string;
  playerIds?: Array<Id<"players">>;
  /** NEO-254 — always written together with `playerIds`, never apart. */
  playerLinks?: Array<{ playerId: Id<"players">; nameOnCard: string }>;
  teamOnCardIds?: Array<Id<"teams">>;
  attributes?: string[];
  isRookie?: boolean;
  isRelic?: boolean;
  printRun?: number;
  cardVariation?: string;
  /** Observed only: folded into `features.autographed`, never stored. */
  autographType?: string;
  /** STORED shape — slot keys on `selectorOptionId`, already resolved. */
  platformData: Doc<"cardChecklist">["platformData"];
  /** Already bounded by the caller; omitted from the row when empty. */
  pendingPlayerNames: string[];
  pendingTeamNames: string[];
  sortOrder: number;
  /** Canonical player names, for Signed By and the listing text. */
  playerNames: string[];
  /** Canonical team names, for the listing text. */
  teamNames?: string[];
  carried?: CarriedCardFields;
  /**
   * NEO-312 — the features map to merge the card's observed facts ONTO,
   * instead of `set.inheritedFeatures`. A parallel copy passes
   * `copyFeaturesForParallel`'s answer here so the insert card's own facts
   * (an autograph, Signed By, a short print) survive the copy. The commit
   * never passes it.
   */
  baseFeatures?: Record<string, string>;
  /**
   * NEO-312 (R2) — the SKU of the old parallel card this copy replaces, when
   * it is clearly the same card. Written as-is instead of generating one.
   */
  keepSku?: string;
  /**
   * NEO-321 (Jason, 2026-10-04) — a parallel copy's `features.parallelName`:
   * the NB name of the parallel row the copy lands on, never a marketplace
   * value. Applied LAST, over the snapshot and over the card's observed
   * `cardVariation` (which keeps its own listing token), so every copy's
   * title names its parallel. The commit never passes it.
   */
  parallelName?: string;
};

export type BuiltCardRow = {
  row: WithoutSystemFields<Doc<"cardChecklist">>;
  /** Everything `generateSku` needs except the random suffix. */
  sku: {
    skuCode?: string;
    sportFallbackLabel: string;
    year: string;
    setName: string;
    cardNumber: string;
  };
};

/**
 * The row a new card is inserted as (without its SKU), plus the SKU inputs.
 * Pure: no database, no clock beyond `now`, no randomness.
 */
export function buildCardRowForInsert(
  card: NewCardRow,
  set: CardRowSetContext,
  now: number,
): BuiltCardRow {
  // NEO-71-74: precedence = the leaf node's complete features snapshot
  // (already resolved at that node's own creation time) < card-observed
  // facts. A fact seen on THIS card (e.g. it's a rookie) beats the
  // inherited values.
  const mergedFeatures: Record<string, string> = {
    ...(card.baseFeatures ?? set.inheritedFeatures ?? {}),
    ...deriveCardObservedFeatures({
      isRookie: card.isRookie,
      isRelic: card.isRelic,
      autographType: card.autographType,
      cardVariation: card.cardVariation,
      attributes: card.attributes,
    }),
  };
  const ownParallelName = card.parallelName?.trim();
  if (ownParallelName) mergedFeatures.parallelName = ownParallelName;
  // A card arriving already-autographed gets the same "just became non-None
  // -> default Signed By from the roster" treatment `setCardFeature` applies
  // for a manual operator edit.
  const wasBlank = (set.inheritedFeatures?.autographed ?? "None") === "None";
  const isNowSet =
    !!mergedFeatures.autographed && mergedFeatures.autographed !== "None";
  const playerNames = card.playerNames;
  if (wasBlank && isNowSet && !mergedFeatures.signedBy && playerNames.length > 0) {
    mergedFeatures.signedBy = playerNames.join(", ");
  }
  const featuresOrUndefined =
    Object.keys(mergedFeatures).length > 0 ? mergedFeatures : undefined;

  // NEO-24/71-74: write-once listing title/description, generated once here
  // at creation time, then freely editable afterward. `previewListingTitle`
  // must be given the same inputs, or a regenerated title disagrees with the
  // one written here.
  const listingInputs: ListingCardInputs = {
    cardNumber: card.cardNumber,
    playerNames,
    year: mergedFeatures.season,
    manufacturer: mergedFeatures.manufacturer,
    manufacturerBrandUnknown: set.manufacturerBrandUnknown,
    setName: set.setNameValue,
    parallelName: mergedFeatures.parallelName,
    isRookie: card.isRookie,
    isRelic: card.isRelic,
    autographed: mergedFeatures.autographed,
    printRun: card.printRun,
    shortPrint: mergedFeatures.shortPrint,
    cardVariation: card.cardVariation,
    teamNames: card.teamNames,
    sport: set.sportValue,
  };
  const listingTitle = assessListingTitle(listingInputs);

  const carried = card.carried ?? {};
  const row: WithoutSystemFields<Doc<"cardChecklist">> = {
    selectorOptionId: card.selectorOptionId,
    cardNumber: card.cardNumber,
    cardName: card.cardName,
    // NEO-26: legacy `team` removed; only teamOnCardIds[] is written.
    playerIds: card.playerIds,
    // NEO-254 — the same list with the printed name attached; see schema.ts.
    // Never written without the ids beside it.
    playerLinks: card.playerLinks,
    teamOnCardIds: card.teamOnCardIds,
    attributes: card.attributes,
    isRookie: card.isRookie,
    isRelic: card.isRelic,
    printRun: card.printRun,
    // NEO-217: `autographType` is NOT written; `features.autographed` is the
    // one truth for "this card is an autograph".
    cardVariation: card.cardVariation,
    platformData: card.platformData,
    ...(featuresOrUndefined ? { features: featuresOrUndefined } : {}),
    listingTitle: listingTitle.title,
    listingDescription: generateListingDescription(listingInputs),
    // NEO-101: only when the core was actually cut (see schema.ts).
    ...(listingTitle.coreFits ? {} : { listingTitleTruncated: true }),
    // NEO-221 / NEO-246 — omitted entirely when empty, so a fully-reviewed
    // commit writes exactly the row it wrote before these fields existed.
    ...(card.pendingPlayerNames.length
      ? { pendingPlayerNames: card.pendingPlayerNames }
      : {}),
    ...(card.pendingTeamNames.length
      ? { pendingTeamNames: card.pendingTeamNames }
      : {}),
    // NEO-312 — a copy's NB-owned rulings, spread only when present so a
    // commit's row is unchanged.
    ...(carried.teamCheckDoneAt !== undefined
      ? { teamCheckDoneAt: carried.teamCheckDoneAt }
      : {}),
    ...(carried.bscTeamName !== undefined
      ? { bscTeamName: carried.bscTeamName }
      : {}),
    ...(carried.teamNoneConfirmedAt !== undefined
      ? { teamNoneConfirmedAt: carried.teamNoneConfirmedAt }
      : {}),
    ...(carried.teamNoneConfirmedByUserId !== undefined
      ? { teamNoneConfirmedByUserId: carried.teamNoneConfirmedByUserId }
      : {}),
    ...(carried.variationOfCardId !== undefined
      ? { variationOfCardId: carried.variationOfCardId }
      : {}),
    ...(carried.variationParentManual !== undefined
      ? { variationParentManual: carried.variationParentManual }
      : {}),
    sortOrder: card.sortOrder,
    lastUpdated: now,
  };

  return {
    row,
    sku: {
      skuCode: set.sportSkuCode,
      sportFallbackLabel: set.sportValue,
      year: mergedFeatures.season ?? "",
      setName: set.setNameValue ?? "",
      cardNumber: card.cardNumber,
    },
  };
}

/**
 * How a new card's player index is kept (NEO-313). `sport` is the CARD's
 * sport, the root of its selector chain, and is asked for lazily: only a card
 * that carries players needs it, and a caller can cache it across a whole
 * page (the commit chunk's `cardSport`).
 */
export type CardRowIndexing = {
  sport: () => Promise<Id<"selectorOptions"> | undefined>;
};

/**
 * Insert a new card row, keep its derived player index (NEO-313), then patch
 * in its SKU.
 *
 * NEO-91: insert-then-patch, as the commit has always done it. The random
 * suffix (not the id) is what makes the SKU unique; the order is kept so the
 * row a commit writes is exactly the row it wrote before this was shared.
 *
 * NEO-313: every card born through here gets its `cardPlayerLinks` rows in
 * the same transaction, exactly as the commit chunk did inline before this
 * was shared — `fresh: true` (the card was inserted a line ago, so there is
 * nothing to diff against) and only when it carries players. Doing it HERE
 * rather than at each call site is what keeps a second caller (the parallel
 * build) from ever minting an unindexed card; `cardPlayerLinks.pin.test.ts`
 * pins it.
 */
export async function insertCardRow(
  ctx: MutationCtx,
  card: NewCardRow,
  set: CardRowSetContext,
  indexing: CardRowIndexing,
): Promise<Id<"cardChecklist">> {
  const built = buildCardRowForInsert(card, set, Date.now());
  // NEO-312 (R2): a rebuilt card that is clearly the old one keeps its SKU,
  // so a label or a listing that already names it still does.
  const id: Id<"cardChecklist"> = await ctx.db.insert(
    "cardChecklist",
    card.keepSku ? { ...built.row, sku: card.keepSku } : built.row,
  );
  if ((card.playerIds ?? []).length > 0) {
    await syncCardPlayerLinks(ctx, id, card.playerIds, await indexing.sport(), {
      fresh: true,
    });
  }
  if (!card.keepSku) {
    await ctx.db.patch(id, {
      sku: generateSku({ ...built.sku, uniqueSuffix: crypto.randomUUID() }),
    });
  }
  return id;
}

/**
 * NEO-312 (hobby A4) — the features a PARALLEL copy of an insert card starts
 * from, before the card's observed facts are applied on top.
 *
 * Three layers, in order:
 *
 *   1. the parallel's own snapshot — the set-level facts of the row the copy
 *      now lives under (`cardType: Parallel`, its release date, …);
 *   2. the insert card's CARD-LEVEL facts — every key whose value on the card
 *      differs from the insert row's snapshot, i.e. a fact observed on that
 *      card or set on it by an operator (an autograph, Signed By, a short
 *      print, a prospect flag). A fact the card merely inherited is not one;
 *      the parallel's own snapshot already speaks for the set level;
 *   3. except on PARALLEL facts, where the parallel's snapshot wins: the keys
 *      in `PARALLEL_FACT_KEYS`, and any key the parallel's snapshot sets to a
 *      different value than the insert's (an operator's parallel-level edit).
 *
 * Pure, and NB data only: both snapshots and the card's features are NB rows.
 */
export const PARALLEL_FACT_KEYS: ReadonlySet<string> = new Set([
  // What the parallel IS. There is no colour or print-run feature key today
  // (`expectedFeatures.ts`); when one is added it belongs in this set.
  "parallelName",
  "cardType",
]);

export function copyFeaturesForParallel(args: {
  insertSnapshot: Record<string, string> | undefined;
  parallelSnapshot: Record<string, string> | undefined;
  insertCardFeatures: Record<string, string> | undefined;
}): Record<string, string> {
  const insertSnapshot = args.insertSnapshot ?? {};
  const parallelSnapshot = args.parallelSnapshot ?? {};
  const out: Record<string, string> = { ...parallelSnapshot };
  const parallelOwns = (key: string): boolean =>
    key in parallelSnapshot &&
    (PARALLEL_FACT_KEYS.has(key) || parallelSnapshot[key] !== insertSnapshot[key]);
  for (const [key, value] of Object.entries(args.insertCardFeatures ?? {})) {
    if (value === insertSnapshot[key]) continue; // inherited, not a card fact
    if (parallelOwns(key)) continue;
    out[key] = value;
  }
  return out;
}
