/**
 * NEO-312 — how a NEW `cardChecklist` row is born, in one place.
 *
 * ## Why this exists
 *
 * Until now the only code that minted a marketplace-derived card row was the
 * insert branch of `commitCardChecklistChunk` (`selectorOptions.ts`): merge the
 * leaf's feature snapshot with what the card itself shows, default Signed By,
 * generate the write-once listing title and description, insert, then patch in
 * the SKU. NEO-312's parallel build copies an insert's cards onto each of its
 * parallels, and every one of those copies has to be born the same way — a
 * copy whose title was generated by a second implementation would disagree
 * with `previewListingTitle`'s Regenerate the moment the two drifted.
 *
 * So the branch body moved here verbatim and both callers share it. What the
 * CALLER still decides is everything that differs between them: the commit
 * resolves players and teams from a review, bounds the pending names and
 * applies the leaf's set-level team default; the parallel build copies those
 * from the insert's card. This module only turns a decided card into a row.
 *
 * ## What it never does
 *
 * It writes no `imageUrls` (a scan belongs to the physical card an operator
 * photographed, not to a checklist entry), queues no enrichment, and reads
 * nothing from the database. `autographType` is folded into
 * `features.autographed` and is not stored (NEO-217).
 */

import type { WithoutSystemFields } from "convex/server";
import type { MutationCtx } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { deriveCardObservedFeatures } from "./features/deriveCardFeatures";
import {
  assessListingTitle,
  generateListingDescription,
  type ListingCardInputs,
} from "./features/generateListing";
import { generateSku } from "./sku";

/** Set-level values resolved once per commit (or per build page). */
export type CardRowSetContext = {
  sportSkuCode?: string;
  sportValue: string;
  setNameValue?: string;
  /** NEO-272 — the manufacturer's brand-unknown ROLE; absent = known. */
  manufacturerBrandUnknown?: boolean;
  /** The leaf row's complete `features` snapshot (NEO-71-74). */
  inheritedFeatures?: Record<string, string>;
};

/**
 * NB-owned fields a COPY carries verbatim from the card it copies (NEO-312).
 * The commit never passes these: a card born from a marketplace sync has no
 * team check, no operator ruling and no variation link yet.
 */
export type CarriedCardFields = Partial<
  Pick<
    Doc<"cardChecklist">,
    | "teamCheckDoneAt"
    | "bscTeamName"
    | "teamNoneConfirmedAt"
    | "teamNoneConfirmedByUserId"
    | "variationOfCardId"
    | "variationParentManual"
  >
>;

/** A card whose content has been decided, ready to become a row. */
export type NewCardRow = {
  selectorOptionId: Id<"selectorOptions">;
  cardNumber: string;
  cardName: string;
  playerIds?: Array<Id<"players">>;
  /** NEO-254 — always written together with `playerIds`, never apart. */
  playerLinks?: Array<{ playerId: Id<"players">; nameOnCard: string }>;
  teamOnCardIds?: Array<Id<"teams">>;
  attributes?: string[];
  isRookie?: boolean;
  isRelic?: boolean;
  printRun?: number;
  cardVariation?: string;
  /** Observed only: folded into `features.autographed`, never stored. */
  autographType?: string;
  /** STORED shape — slot keys on `selectorOptionId`, already resolved. */
  platformData: Doc<"cardChecklist">["platformData"];
  /** Already bounded by the caller; omitted from the row when empty. */
  pendingPlayerNames: string[];
  pendingTeamNames: string[];
  sortOrder: number;
  /** Canonical player names, for Signed By and the listing text. */
  playerNames: string[];
  /** Canonical team names, for the listing text. */
  teamNames?: string[];
  carried?: CarriedCardFields;
};

export type BuiltCardRow = {
  row: WithoutSystemFields<Doc<"cardChecklist">>;
  /** Everything `generateSku` needs except the random suffix. */
  sku: {
    skuCode?: string;
    sportFallbackLabel: string;
    year: string;
    setName: string;
    cardNumber: string;
  };
};

/**
 * The row a new card is inserted as (without its SKU), plus the SKU inputs.
 * Pure: no database, no clock beyond `now`, no randomness.
 */
export function buildCardRowForInsert(
  card: NewCardRow,
  set: CardRowSetContext,
  now: number,
): BuiltCardRow {
  // NEO-71-74: precedence = the leaf node's complete features snapshot
  // (already resolved at that node's own creation time) < card-observed
  // facts. A fact seen on THIS card (e.g. it's a rookie) beats the
  // inherited values.
  const mergedFeatures: Record<string, string> = {
    ...(set.inheritedFeatures ?? {}),
    ...deriveCardObservedFeatures({
      isRookie: card.isRookie,
      isRelic: card.isRelic,
      autographType: card.autographType,
      cardVariation: card.cardVariation,
      attributes: card.attributes,
    }),
  };
  // A card arriving already-autographed gets the same "just became non-None
  // -> default Signed By from the roster" treatment `setCardFeature` applies
  // for a manual operator edit.
  const wasBlank = (set.inheritedFeatures?.autographed ?? "None") === "None";
  const isNowSet =
    !!mergedFeatures.autographed && mergedFeatures.autographed !== "None";
  const playerNames = card.playerNames;
  if (wasBlank && isNowSet && !mergedFeatures.signedBy && playerNames.length > 0) {
    mergedFeatures.signedBy = playerNames.join(", ");
  }
  const featuresOrUndefined =
    Object.keys(mergedFeatures).length > 0 ? mergedFeatures : undefined;

  // NEO-24/71-74: write-once listing title/description, generated once here
  // at creation time, then freely editable afterward. `previewListingTitle`
  // must be given the same inputs, or a regenerated title disagrees with the
  // one written here.
  const listingInputs: ListingCardInputs = {
    cardNumber: card.cardNumber,
    playerNames,
    year: mergedFeatures.season,
    manufacturer: mergedFeatures.manufacturer,
    manufacturerBrandUnknown: set.manufacturerBrandUnknown,
    setName: set.setNameValue,
    parallelName: mergedFeatures.parallelName,
    isRookie: card.isRookie,
    isRelic: card.isRelic,
    autographed: mergedFeatures.autographed,
    printRun: card.printRun,
    shortPrint: mergedFeatures.shortPrint,
    cardVariation: card.cardVariation,
    teamNames: card.teamNames,
    sport: set.sportValue,
  };
  const listingTitle = assessListingTitle(listingInputs);

  const carried = card.carried ?? {};
  const row: WithoutSystemFields<Doc<"cardChecklist">> = {
    selectorOptionId: card.selectorOptionId,
    cardNumber: card.cardNumber,
    cardName: card.cardName,
    // NEO-26: legacy `team` removed; only teamOnCardIds[] is written.
    playerIds: card.playerIds,
    // NEO-254 — the same list with the printed name attached; see schema.ts.
    // Never written without the ids beside it.
    playerLinks: card.playerLinks,
    teamOnCardIds: card.teamOnCardIds,
    attributes: card.attributes,
    isRookie: card.isRookie,
    isRelic: card.isRelic,
    printRun: card.printRun,
    // NEO-217: `autographType` is NOT written; `features.autographed` is the
    // one truth for "this card is an autograph".
    cardVariation: card.cardVariation,
    platformData: card.platformData,
    ...(featuresOrUndefined ? { features: featuresOrUndefined } : {}),
    listingTitle: listingTitle.title,
    listingDescription: generateListingDescription(listingInputs),
    // NEO-101: only when the core was actually cut (see schema.ts).
    ...(listingTitle.coreFits ? {} : { listingTitleTruncated: true }),
    // NEO-221 / NEO-246 — omitted entirely when empty, so a fully-reviewed
    // commit writes exactly the row it wrote before these fields existed.
    ...(card.pendingPlayerNames.length
      ? { pendingPlayerNames: card.pendingPlayerNames }
      : {}),
    ...(card.pendingTeamNames.length
      ? { pendingTeamNames: card.pendingTeamNames }
      : {}),
    // NEO-312 — a copy's NB-owned rulings, spread only when present so a
    // commit's row is unchanged.
    ...(carried.teamCheckDoneAt !== undefined
      ? { teamCheckDoneAt: carried.teamCheckDoneAt }
      : {}),
    ...(carried.bscTeamName !== undefined
      ? { bscTeamName: carried.bscTeamName }
      : {}),
    ...(carried.teamNoneConfirmedAt !== undefined
      ? { teamNoneConfirmedAt: carried.teamNoneConfirmedAt }
      : {}),
    ...(carried.teamNoneConfirmedByUserId !== undefined
      ? { teamNoneConfirmedByUserId: carried.teamNoneConfirmedByUserId }
      : {}),
    ...(carried.variationOfCardId !== undefined
      ? { variationOfCardId: carried.variationOfCardId }
      : {}),
    ...(carried.variationParentManual !== undefined
      ? { variationParentManual: carried.variationParentManual }
      : {}),
    sortOrder: card.sortOrder,
    lastUpdated: now,
  };

  return {
    row,
    sku: {
      skuCode: set.sportSkuCode,
      sportFallbackLabel: set.sportValue,
      year: mergedFeatures.season ?? "",
      setName: set.setNameValue ?? "",
      cardNumber: card.cardNumber,
    },
  };
}

/**
 * Insert a new card row, then patch in its SKU.
 *
 * NEO-91: insert-then-patch, as the commit has always done it. The random
 * suffix (not the id) is what makes the SKU unique; the order is kept so the
 * row a commit writes is exactly the row it wrote before this was shared.
 */
export async function insertCardRow(
  ctx: { db: Pick<MutationCtx["db"], "insert" | "patch"> },
  card: NewCardRow,
  set: CardRowSetContext,
): Promise<Id<"cardChecklist">> {
  const built = buildCardRowForInsert(card, set, Date.now());
  const id: Id<"cardChecklist"> = await ctx.db.insert("cardChecklist", built.row);
  await ctx.db.patch(id, {
    sku: generateSku({ ...built.sku, uniqueSuffix: crypto.randomUUID() }),
  });
  return id;
}
